services:
  sqldb:
    container_name: kimai-tracker-sqldb
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-innodb-adaptive-hash-index
      - --innodb-buffer-pool-size=128M
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MARIADB_USER", "-p$$MARIADB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  kimai:
    container_name: kimai-tracker-kimai
    image: kimai/kimai2:apache
    volumes:
      - data:/opt/kimai/var/data
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=${ADMIN_EMAIL}
      - ADMINPASS=${ADMIN_PASSWORD}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@sqldb:3306/${DATABASE_NAME}?charset=utf8mb4&serverVersion=mariadb-10.11.0
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped
    depends_on:
      sqldb:
        condition: service_healthy

volumes:
  data:
    driver: local
  mysql:
    driver: local
