services:
  sqldb:
    container_name: kimai-tracker-sqldb
    image: mariadb:10.11
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    container_name: kimai-tracker-kimai
    image: kimai/kimai2:apache
    volumes:
      - data:/opt/kimai/var/data
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=${ADMIN_EMAIL}
      - ADMINPASS=${ADMIN_PASSWORD}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@sqldb:3306/${DATABASE_NAME}?charset=utf8mb4&serverVersion=mariadb-10.11.0
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped
    depends_on:
      sqldb:
        condition: service_healthy

volumes:
  data:
  mysql:
